// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Soltec.DocParser.Uso;

#nullable disable

namespace Soltec.DocParser.Uso.Migrations
{
    [DbContext(typeof(UsoDbContext))]
    partial class UsoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Soltec.DocParser.Uso.RegistroUso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoIaUsd")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracionMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreArchivo")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Paginas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProveedorIa")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long>("TokensEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TokensSalida")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsoIa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("IdUsuario", "FechaUtc");

                    b.ToTable("RegistrosUso", (string)null);
                });

            modelBuilder.Entity("Soltec.DocParser.Uso.RegistroUsoIa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoUsd")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Exitosa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long>("RegistroUsoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokensEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokensEntradaCache")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokensSalida")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegistroUsoId");

                    b.ToTable("RegistrosUsoIa", (string)null);
                });

            modelBuilder.Entity("Soltec.DocParser.Uso.RegistroUsoIa", b =>
                {
                    b.HasOne("Soltec.DocParser.Uso.RegistroUso", null)
                        .WithMany("LlamadasIa")
                        .HasForeignKey("RegistroUsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Soltec.DocParser.Uso.RegistroUso", b =>
                {
                    b.Navigation("LlamadasIa");
                });
#pragma warning restore 612, 618
        }
    }
}
